# Generated by Django 5.0.4 on 2024-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
