# Generated by Django 5.0.4 on 2024-05-18 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام محل ثبت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام بیمار'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.IntegerField(unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.organization', verbose_name='محل ثبت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='تلفن'),
        ),
    ]
