# Generated by Django 5.0.4 on 2024-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_patient_date_created_patient_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='file_number',
            field=models.BigIntegerField(default=1, verbose_name='شماره پرونده مرکز'),
            preserve_default=False,
        ),
    ]
