# Generated by Django 5.0.4 on 2024-05-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_patient_file_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/', verbose_name='تصویر')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('patient_national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.patient', verbose_name='تصاویر پرونده')),
            ],
        ),
    ]
