# Generated by Django 5.0.4 on 2024-05-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
